import type { BBSTestItem } from '../types';

export const BBS_TEST_ITEMS: BBSTestItem[] = [
  {
    id: 1,
    name: 'Sitting to Standing',
    nameKo: '앉은 자세에서 일어서기',
    description: 'Please stand up. Try not to use your hands for support.',
    instructions: 'Patient sits on a standard height chair. Ask patient to stand without using hands.',
    instructionsKo: '표준 높이의 의자에 앉은 상태에서 손을 사용하지 않고 일어서도록 합니다.',
    scoringCriteria: [
      { score: 4, description: 'Able to stand without using hands and stabilize independently', descriptionKo: '손을 사용하지 않고 일어서서 독립적으로 안정화할 수 있음' },
      { score: 3, description: 'Able to stand independently using hands', descriptionKo: '손을 사용하여 독립적으로 일어설 수 있음' },
      { score: 2, description: 'Able to stand using hands after several tries', descriptionKo: '여러 번 시도 후 손을 사용하여 일어설 수 있음' },
      { score: 1, description: 'Needs minimal aid to stand or stabilize', descriptionKo: '일어서거나 안정화하기 위해 최소한의 도움이 필요함' },
      { score: 0, description: 'Needs moderate or maximal assist to stand', descriptionKo: '일어서기 위해 중등도 또는 최대 도움이 필요함' },
    ],
  },
  {
    id: 2,
    name: 'Standing Unsupported',
    nameKo: '지지 없이 서 있기',
    description: 'Please stand for two minutes without holding onto anything.',
    instructions: 'Patient stands without support for 2 minutes.',
    instructionsKo: '지지 없이 2분간 서 있도록 합니다.',
    timeRequirement: 120,
    scoringCriteria: [
      { score: 4, description: 'Able to stand safely 2 minutes', descriptionKo: '2분간 안전하게 서 있을 수 있음' },
      { score: 3, description: 'Able to stand 2 minutes with supervision', descriptionKo: '감독 하에 2분간 서 있을 수 있음' },
      { score: 2, description: 'Able to stand 30 seconds unsupported', descriptionKo: '지지 없이 30초간 서 있을 수 있음' },
      { score: 1, description: 'Needs several tries to stand 30 seconds unsupported', descriptionKo: '지지 없이 30초간 서기 위해 여러 번 시도가 필요함' },
      { score: 0, description: 'Unable to stand 30 seconds unsupported', descriptionKo: '지지 없이 30초간 서 있을 수 없음' },
    ],
  },
  {
    id: 3,
    name: 'Sitting Unsupported',
    nameKo: '지지 없이 앉아 있기',
    description: 'Please sit with arms folded for 2 minutes.',
    instructions: 'Patient sits with feet flat on floor, arms folded.',
    instructionsKo: '발을 바닥에 평평하게 놓고 팔을 접은 채로 앉아 있도록 합니다.',
    timeRequirement: 120,
    scoringCriteria: [
      { score: 4, description: 'Able to sit safely and securely 2 minutes', descriptionKo: '2분간 안전하고 확실하게 앉아 있을 수 있음' },
      { score: 3, description: 'Able to sit 2 minutes under supervision', descriptionKo: '감독 하에 2분간 앉아 있을 수 있음' },
      { score: 2, description: 'Able to sit 30 seconds', descriptionKo: '30초간 앉아 있을 수 있음' },
      { score: 1, description: 'Able to sit 10 seconds', descriptionKo: '10초간 앉아 있을 수 있음' },
      { score: 0, description: 'Unable to sit without support 10 seconds', descriptionKo: '지지 없이 10초간 앉아 있을 수 없음' },
    ],
  },
  {
    id: 4,
    name: 'Standing to Sitting',
    nameKo: '선 자세에서 앉기',
    description: 'Please sit down.',
    instructions: 'Patient transitions from standing to sitting on a chair.',
    instructionsKo: '서 있는 자세에서 의자에 앉도록 합니다.',
    scoringCriteria: [
      { score: 4, description: 'Sits safely with minimal use of hands', descriptionKo: '손을 최소한으로 사용하여 안전하게 앉음' },
      { score: 3, description: 'Controls descent by using hands', descriptionKo: '손을 사용하여 하강을 제어함' },
      { score: 2, description: 'Uses back of legs against chair to control descent', descriptionKo: '다리 뒤쪽을 의자에 대어 하강을 제어함' },
      { score: 1, description: 'Sits independently but has uncontrolled descent', descriptionKo: '독립적으로 앉지만 제어되지 않은 하강' },
      { score: 0, description: 'Needs assistance to sit', descriptionKo: '앉기 위해 도움이 필요함' },
    ],
  },
  {
    id: 5,
    name: 'Transfers',
    nameKo: '이동하기',
    description: 'Move from chair to chair (or bed to chair and back).',
    instructions: 'Arrange chairs for pivot transfer. Ask patient to transfer one way and then back.',
    instructionsKo: '회전 이동을 위해 의자를 배치합니다. 환자에게 한 방향으로 이동한 후 다시 돌아오도록 합니다.',
    scoringCriteria: [
      { score: 4, description: 'Able to transfer safely with minor use of hands', descriptionKo: '손을 약간 사용하여 안전하게 이동할 수 있음' },
      { score: 3, description: 'Able to transfer safely definite need of hands', descriptionKo: '손을 확실히 사용하여 안전하게 이동할 수 있음' },
      { score: 2, description: 'Able to transfer with verbal cuing and/or supervision', descriptionKo: '언어적 지시 및/또는 감독하에 이동할 수 있음' },
      { score: 1, description: 'Needs one person to assist', descriptionKo: '한 명의 도움이 필요함' },
      { score: 0, description: 'Needs two people to assist or supervise to be safe', descriptionKo: '안전을 위해 두 명의 도움 또는 감독이 필요함' },
    ],
  },
  {
    id: 6,
    name: 'Standing with Eyes Closed',
    nameKo: '눈 감고 서 있기',
    description: 'Please close your eyes and stand still for 10 seconds.',
    instructions: 'Patient stands with eyes closed for 10 seconds.',
    instructionsKo: '눈을 감고 10초간 서 있도록 합니다.',
    timeRequirement: 10,
    scoringCriteria: [
      { score: 4, description: 'Able to stand 10 seconds safely', descriptionKo: '10초간 안전하게 서 있을 수 있음' },
      { score: 3, description: 'Able to stand 10 seconds with supervision', descriptionKo: '감독 하에 10초간 서 있을 수 있음' },
      { score: 2, description: 'Able to stand 3 seconds', descriptionKo: '3초간 서 있을 수 있음' },
      { score: 1, description: 'Unable to keep eyes closed 3 seconds but stays safely', descriptionKo: '눈을 3초간 감고 있을 수 없지만 안전하게 서 있음' },
      { score: 0, description: 'Needs help to keep from falling', descriptionKo: '넘어지지 않기 위해 도움이 필요함' },
    ],
  },
  {
    id: 7,
    name: 'Standing with Feet Together',
    nameKo: '두 발 모으고 서 있기',
    description: 'Place your feet together and stand without holding.',
    instructions: 'Patient stands with feet together for 1 minute.',
    instructionsKo: '두 발을 모으고 1분간 서 있도록 합니다.',
    timeRequirement: 60,
    scoringCriteria: [
      { score: 4, description: 'Able to place feet together independently and stand 1 minute safely', descriptionKo: '독립적으로 발을 모으고 1분간 안전하게 서 있을 수 있음' },
      { score: 3, description: 'Able to place feet together independently and stand 1 minute with supervision', descriptionKo: '독립적으로 발을 모으고 감독 하에 1분간 서 있을 수 있음' },
      { score: 2, description: 'Able to place feet together independently and hold 30 seconds', descriptionKo: '독립적으로 발을 모으고 30초간 유지할 수 있음' },
      { score: 1, description: 'Needs help to attain position but able to stand 15 seconds', descriptionKo: '자세를 취하는 데 도움이 필요하지만 15초간 서 있을 수 있음' },
      { score: 0, description: 'Needs help to attain position and unable to hold 15 seconds', descriptionKo: '자세를 취하는 데 도움이 필요하고 15초간 유지할 수 없음' },
    ],
  },
  {
    id: 8,
    name: 'Reaching Forward with Outstretched Arm',
    nameKo: '팔 뻗어 앞으로 내밀기',
    description: 'Lift arm to 90 degrees. Stretch out your fingers and reach forward as far as you can.',
    instructions: 'Patient lifts arm to 90° and reaches forward while examiner measures distance.',
    instructionsKo: '팔을 90도로 들어올리고 앞으로 최대한 뻗도록 합니다. 검사자가 거리를 측정합니다.',
    scoringCriteria: [
      { score: 4, description: 'Can reach forward confidently >25 cm (10 inches)', descriptionKo: '자신 있게 25cm(10인치) 이상 앞으로 뻗을 수 있음' },
      { score: 3, description: 'Can reach forward >12 cm (5 inches)', descriptionKo: '12cm(5인치) 이상 앞으로 뻗을 수 있음' },
      { score: 2, description: 'Can reach forward >5 cm (2 inches)', descriptionKo: '5cm(2인치) 이상 앞으로 뻗을 수 있음' },
      { score: 1, description: 'Reaches forward but needs supervision', descriptionKo: '앞으로 뻗지만 감독이 필요함' },
      { score: 0, description: 'Loses balance while trying/requires external support', descriptionKo: '시도하는 동안 균형을 잃거나 외부 지지가 필요함' },
    ],
  },
  {
    id: 9,
    name: 'Retrieving Object from Floor',
    nameKo: '바닥에서 물건 집어 올리기',
    description: 'Pick up the shoe/slipper which is placed in front of your feet.',
    instructions: 'Place a shoe/slipper in front of patient\'s feet. Ask patient to pick it up.',
    instructionsKo: '환자의 발 앞에 신발/슬리퍼를 놓습니다. 환자에게 집어 올리도록 합니다.',
    scoringCriteria: [
      { score: 4, description: 'Able to pick up slipper safely and easily', descriptionKo: '안전하고 쉽게 슬리퍼를 집을 수 있음' },
      { score: 3, description: 'Able to pick up slipper but needs supervision', descriptionKo: '슬리퍼를 집을 수 있지만 감독이 필요함' },
      { score: 2, description: 'Unable to pick up but reaches 2-5 cm from slipper and keeps balance independently', descriptionKo: '집을 수 없지만 슬리퍼에서 2-5cm 거리까지 도달하고 독립적으로 균형을 유지함' },
      { score: 1, description: 'Unable to pick up and needs supervision while trying', descriptionKo: '집을 수 없고 시도하는 동안 감독이 필요함' },
      { score: 0, description: 'Unable to try/needs assist to keep from losing balance or falling', descriptionKo: '시도할 수 없음/균형을 잃거나 넘어지지 않기 위해 도움이 필요함' },
    ],
  },
  {
    id: 10,
    name: 'Turning to Look Behind',
    nameKo: '뒤돌아보기 (좌/우)',
    description: 'Turn to look directly behind you over your left shoulder. Repeat to the right.',
    instructions: 'Patient turns to look behind over each shoulder while standing.',
    instructionsKo: '서 있는 상태에서 각 어깨 너머로 뒤를 돌아보도록 합니다.',
    scoringCriteria: [
      { score: 4, description: 'Looks behind from both sides and weight shifts well', descriptionKo: '양쪽에서 뒤를 돌아보고 체중 이동이 잘됨' },
      { score: 3, description: 'Looks behind one side only, other side shows less weight shift', descriptionKo: '한쪽만 뒤를 돌아보고, 다른 쪽은 체중 이동이 적음' },
      { score: 2, description: 'Turns sideways only but maintains balance', descriptionKo: '옆으로만 돌지만 균형을 유지함' },
      { score: 1, description: 'Needs supervision when turning', descriptionKo: '돌 때 감독이 필요함' },
      { score: 0, description: 'Needs assist to keep from losing balance or falling', descriptionKo: '균형을 잃거나 넘어지지 않기 위해 도움이 필요함' },
    ],
  },
  {
    id: 11,
    name: 'Turning 360 Degrees',
    nameKo: '360도 회전하기',
    description: 'Turn completely around in a full circle. Pause. Then turn a full circle in the other direction.',
    instructions: 'Patient performs a complete 360° turn in each direction.',
    instructionsKo: '각 방향으로 360도 완전히 회전하도록 합니다.',
    timeRequirement: 4,
    scoringCriteria: [
      { score: 4, description: 'Able to turn 360° safely in 4 seconds or less', descriptionKo: '4초 이내에 안전하게 360도 회전할 수 있음' },
      { score: 3, description: 'Able to turn 360° safely one side only 4 seconds or less', descriptionKo: '한 방향으로만 4초 이내에 안전하게 360도 회전할 수 있음' },
      { score: 2, description: 'Able to turn 360° safely but slowly', descriptionKo: '안전하게 360도 회전할 수 있지만 느림' },
      { score: 1, description: 'Needs close supervision or verbal cuing', descriptionKo: '밀착 감독 또는 언어적 지시가 필요함' },
      { score: 0, description: 'Needs assistance while turning', descriptionKo: '회전하는 동안 도움이 필요함' },
    ],
  },
  {
    id: 12,
    name: 'Placing Alternate Foot on Stool',
    nameKo: '발판 위에 발 교대로 올리기',
    description: 'Place each foot alternately on the step/stool. Continue until each foot has touched 4 times.',
    instructions: 'Patient places each foot alternately on a stool (8 times total in 20 seconds).',
    instructionsKo: '발판 위에 각 발을 교대로 올리도록 합니다 (20초 내에 총 8회).',
    timeRequirement: 20,
    scoringCriteria: [
      { score: 4, description: 'Able to stand independently and safely, completes 8 steps in 20 seconds', descriptionKo: '독립적이고 안전하게 서서 20초 내에 8회 완료할 수 있음' },
      { score: 3, description: 'Able to stand independently and completes 8 steps in >20 seconds', descriptionKo: '독립적으로 서서 20초 이상에 8회 완료할 수 있음' },
      { score: 2, description: 'Able to complete 4 steps without aid with supervision', descriptionKo: '도움 없이 감독 하에 4회 완료할 수 있음' },
      { score: 1, description: 'Able to complete >2 steps, needs minimal assist', descriptionKo: '2회 이상 완료할 수 있고, 최소한의 도움이 필요함' },
      { score: 0, description: 'Needs assistance to keep from falling/unable to try', descriptionKo: '넘어지지 않기 위해 도움이 필요함/시도할 수 없음' },
    ],
  },
  {
    id: 13,
    name: 'Standing with One Foot in Front',
    nameKo: '한 발 앞에 다른 발 두고 서기 (일렬로 서기)',
    description: 'Place one foot directly in front of the other. If you feel that you cannot place your foot directly in front, try to step far enough ahead that the heel of your forward foot is ahead of the toes of the other foot.',
    instructions: 'Patient stands in tandem stance (heel to toe) for 30 seconds.',
    instructionsKo: '일렬 자세(발뒤꿈치에서 발끝까지)로 30초간 서 있도록 합니다.',
    timeRequirement: 30,
    scoringCriteria: [
      { score: 4, description: 'Able to place foot tandem independently and hold 30 seconds', descriptionKo: '독립적으로 일렬로 발을 놓고 30초간 유지할 수 있음' },
      { score: 3, description: 'Able to place foot ahead of other independently and hold 30 seconds', descriptionKo: '독립적으로 한 발을 다른 발 앞에 놓고 30초간 유지할 수 있음' },
      { score: 2, description: 'Able to take small step independently and hold 30 seconds', descriptionKo: '독립적으로 작은 발걸음을 딛고 30초간 유지할 수 있음' },
      { score: 1, description: 'Needs help to step but can hold 15 seconds', descriptionKo: '발을 딛는 데 도움이 필요하지만 15초간 유지할 수 있음' },
      { score: 0, description: 'Loses balance while stepping or standing', descriptionKo: '발을 딛거나 서 있는 동안 균형을 잃음' },
    ],
  },
  {
    id: 14,
    name: 'Standing on One Foot',
    nameKo: '한 발로 서 있기',
    description: 'Stand on one leg as long as you can without holding on.',
    instructions: 'Patient stands on one leg for as long as possible (up to 10 seconds).',
    instructionsKo: '한 발로 최대한 오래 서 있도록 합니다 (최대 10초).',
    timeRequirement: 10,
    scoringCriteria: [
      { score: 4, description: 'Able to lift leg independently and hold >10 seconds', descriptionKo: '독립적으로 다리를 들어 10초 이상 유지할 수 있음' },
      { score: 3, description: 'Able to lift leg independently and hold 5-10 seconds', descriptionKo: '독립적으로 다리를 들어 5-10초간 유지할 수 있음' },
      { score: 2, description: 'Able to lift leg independently and hold ≥3 seconds', descriptionKo: '독립적으로 다리를 들어 3초 이상 유지할 수 있음' },
      { score: 1, description: 'Tries to lift leg, unable to hold 3 seconds but remains standing independently', descriptionKo: '다리를 들려고 시도하지만 3초간 유지할 수 없으나 독립적으로 서 있음' },
      { score: 0, description: 'Unable to try or needs assist to prevent fall', descriptionKo: '시도할 수 없거나 넘어지지 않기 위해 도움이 필요함' },
    ],
  },
];

export function getTestItemById(id: number): BBSTestItem | undefined {
  return BBS_TEST_ITEMS.find(item => item.id === id);
}

export function calculateTotalScore(results: { testItemId: number; score: number | null }[]): number {
  return results.reduce((total, result) => total + (result.score ?? 0), 0);
}
